fix: point to 'pomo' without the py suffix

diff --git a/timew_pom b/timew_pom
--- a/timew_pom
+++ b/timew_pom
@@ -57,15 +57,15 @@ else
   fi
 fi
 
-if [[ ! -f ~/bin/pomo.py ]]; then
-  echo "Error: ~/bin/pomo.py not found." >&2
+if [[ ! -f ~/bin/pomo ]]; then
+  echo "Error: ~/bin/pomo not found." >&2
   exit 1
 fi
 
 # Check if uv is installed, if not revert to using python directly
 if command -v uv >/dev/null 2>&1; then
-  uv run ~/bin/pomo.py "$minutes" -w $(( $(tput cols) * 80 / 100 ))
+  uv run ~/bin/pomo "$minutes" -w $(( $(tput cols) * 80 / 100 ))
 else
-  python3 ~/bin/pomo.py "$minutes" -w $(( $(tput cols) * 80 / 100 ))
+  python3 ~/bin/pomo "$minutes" -w $(( $(tput cols) * 80 / 100 ))
 fi
 # vim: ft=sh
